name: 01 Build pipeline

on:
  workflow_dispatch:
  workflow_call:

jobs:
  # name of job. free choice, could also give a name
  build:
    # required to fix an issue when test results failed because
    # checks: write and pull-requests: write were needed
    permissions:
      contents: read
      issues: read
      checks: write
    # runner
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'    # corrected 'java-versions' to 'java-version'
        distribution: 'temurin'
        cache: maven

    # compile
    - name: Build with Maven
      run: mvn clean package -B -Dmaven.test.skip

    - run: mkdir candidate-binary && cp target/*.jar candidate-binary

    # test
    - name: Run Maven tests
      run: mvn test

    - run: mkdir test-results && cp target/*-reports/TEST-*.xml test-results

    - uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2.0.0
      if: always()
      with: 
        junit_files: "test-results/**/*.xml"
