name: 00 - Main CI / CD Pipeline

on:
  push:
    branches:
      - main  # Use list format for branches
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:

jobs:
  build:
    name: Build  # Correct indentation here
    uses: ./.github/workflows/build.yml
    secrets: inherit  # Inherit secrets from the repository or organization level
